name: Continuous Integration

on:
  pull_request:
    branches: 
      - master
  push:
    branches:
      - master
jobs:
  build:
    name: Build docker image and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from Github
        uses: actions/checkout@v3