name: Continuous Integration

on:
  pull_request:
    branches: 
      - master
  push:
    branches:
      - master
jobs:
  build:
    name: Build docker image and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from Github
        uses: actions/checkout@v3
      - name: Run tests
        run: >
          echo "Tests are okay"
      - name: Login to DockerHub
        uses: docker/login-actions@v2
        if: ${{ github.event_name == 'push' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image to DockerHub
        uses: docker/build-push-action@v4.0.0
        if: ${{ github.event_name == 'push' }}
        with:
          context: ./web
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/financial-adm:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/financial-adm:latest